{
  "D": {
    "woot": "I am a debug message"
  },
  "I": {
    "woot": "I am an informational message"
  },
  "S": {
    "woot": "I am a success message",
    "except": "properly caught exception"
  },
  "W": {
    "woot": "I am a warning message"
  },
  "E": {
    "woot": "I am an error message"
  },
  "F": {
    "woot": "I am a fatal message %d",
    "fatale": "This message should cause an exception"
  }
}